version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bookstore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookstore_db
      - POSTGRES_USER=bookstore_user
      - POSTGRES_PASSWORD=bookstore_pass
    ports:
      - "5432:5432"
    networks:
      - bookstore_network  

  web:
    build: .
    container_name: bookstore_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=bookstore_db
      - DB_USER=bookstore_user
      - DB_PASSWORD=bookstore_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - bookstore_network 

volumes:
  postgres_data:


networks:
  bookstore_network:
    driver: bridge